swagger: '3.0.0'
info:
  title: Category Model API
  description: API related to Category models
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /api/category/all:
    get:
      summary: Fetch All Categories
      description: Endpoint to fetch all Categories
      tags:
        - Category Model
      security:
        - JWT: []
      responses:
        200:
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Fetch all Categories successfully
                  result:
                    type: array
                    items:
                      type: object
                      properties:
                        categoryName:
                          type: string
                          example: "Kutty Stories"
                        packageId:
                          type: string
                          example: "670d2fd920824883c3100257"
                        description:
                          type: string
                          example: "Kutty Stories"
                        imageUrl:
                          type: string
                          example: "upload/category/sample.jpg"
                        isActive:
                          type: boolean
                          example: true
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: An error occurred

  /api/category/by-package/{packageId}:
    get:
      summary: Fetch Categories by Package ID
      description: Endpoint to fetch categories by a given Package ID
      tags:
        - Category Model
      parameters:
        - name: packageId
          in: path
          required: true
          description: The ID of the package
          schema:
            type: string
            example: "670d2fd920824883c3100257"
      security:
        - JWT: []
      responses:
        200:
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Fetch Categories by Package ID successfully
                  result:
                    type: array
                    items:
                      type: object
                      properties:
                        categoryName:
                          type: string
                          example: "Kutty Stories"
                        packageId:
                          type: string
                          example: "670d2fd920824883c3100257"
                        description:
                          type: string
                          example: "Kutty Stories"
                        imageUrl:
                          type: string
                          example: "upload/category/sample.jpg"
                        isActive:
                          type: boolean
                          example: true
        404:
          description: Categories not found for the given package
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: No categories found for this package
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: An error occurred


components:
  securitySchemes:
    JWT:
      type: apiKey
      in: header
      name: Authorization
      description: JWT Bearer token
