swagger: '3.0.0'
info:
  title: Users Model API
  description: API related to Users models
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /api/user/register/:
    post:
      summary: Register Users
      description: Endpoint for registering users
      tags:
        - Users Model
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullName:
                  type: string
                  example: JohnDoe
                mobileNumber:
                  type: integer
                  example: 1234567890
                dob:
                  type: string
                  format: date
                  example: 2000-01-01
                gender:
                  type: string
                  enum:
                    - male
                    - female
                  example: male
                userType:
                  type: string
                  enum:
                    - child
                    - teenager
                    - adult
                  example: adult
                email:
                  type: string
                  format: email
                  example: johndoe@example.com
                  nullable: true                 

      responses:
        200:
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Registered user successfully
                  result:
                    type: string
                    example: ''
        401:
          description: Unauthorized response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized user
  /api/user/verify-otp:
    post:
      summary: Verify OTP
      description: Endpoint to verify OTP
      tags:
        - Users Model
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mobileNumber:
                  type: integer
                  example: 1234567890
                otp:
                  type: string
                  example: 123456
                deviceId:
                  type: string
                  example: 123456
                deviceType:
                  type: string
                  example: web
      responses:
        200:
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: OTP verified successfully
                  result:
                    type: object
                    properties:
                      token:
                        type: string
                        example: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        401:
          description: Unauthorized response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized user
  /api/user/upload-avatar:
    post:
      summary: Upload Avatar
      description: Endpoint to upload user avatar
      tags:
        - Users Model
      security:
        - JWT: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
                  description: The image file to upload (jpg or png)
      responses:
        200:
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Avatar uploaded successfully
                  imageUrl:
                    type: string
                    example: '/upload/avatar/filename.png'
        400:
          description: Bad Request response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Bad request
        401:
          description: Unauthorized response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized user

/api/user/send-otp:
    post:
      summary: Send OTP
      description: Endpoint to Send OTP
      tags:
        - Users Model
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mobileNumber:
                  type: integer
                  example: 1234567890               
      responses:
        200:
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: OTP Sent successfully
                  result:
                    type: object
                    properties:
                      token:
                        type: string
                        example: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        401:
          description: Unauthorized response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized user

/api/user/profile/{userId}:
    get:
      summary: Fetch profile by user ID
      description: Endpoint to fetch profile by user ID
      tags:
        - Users Model
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
            example: "670d2fd920824883c3100257"
      security:
        - JWT: []
      responses:
        200:
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Fetch users by user ID successfully
                  result:
                    type: array
                    items:
                      type: object                     
        404:
          description: User not found for the given UserId
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: No profile found for this userId
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: An error occurred

/api/user/courseMaterialTrack/{userId}:
    get:
      summary: Fetch courseMaterialTrack percentage by user ID
      description: Endpoint to fetch profile by user ID
      tags:
        - Users Model
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
            example: "670d2fd920824883c3100257"
      security:
        - JWT: []
      responses:
        200:
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Fetch courseMaterialTrack percentage by user ID successfully
                  result:
                    type: array
                    items:
                      type: object                     
        404:
          description: courseMaterialTrack not found for the given UserId
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: No courseMaterialTrack found for this userId
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: An error occurred

/api/user/profileUpdate/{userId}:
    put:
      summary: update profile by user ID
      description: Endpoint to update profile by user ID
      tags:
        - Users Model
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullName:
                  type: string
                  example: JohnDoe
                mobileNumber:
                  type: integer
                  example: 1234567890,
                gender:
                  type: string
                  enum:
                    - male
                    - female
                  example: male
                dob:
                  type: string
                  format: date
                  example: 2000-01-01
                userType:
                  type: string
                  enum:
                    - child
                    - teenager
                    - adult
                  example: adult
                email:
                  type: string
                  format: email
                  example: johndoe@example.com
                  nullable: true                 
                parentName:
                  type: string
                  example: Danial
                  nullable: true
                parentDob:
                  type: date
                  format: date
                  example: 1985-01-01
                  nullable: true 
                interest:
                  type: string
                  example: Craft
                  nullable: true  

      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
            example: "670d2fd920824883c3100257"
      security:
        - JWT: []
      responses:
        200:
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Fetch users by user ID successfully
                  result:
                    type: array
                    items:
                      type: object                     
        404:
          description: User not found for the given UserId
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: No profile found for this userId
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: An error occurred

components:
  securitySchemes:
    JWT:
      type: apiKey
      in: header
      name: Authorization
      description: JWT Bearer token
